sudo: required
dist: trusty

language: haxe

os:
  - linux
  # - osx
  
haxe:
  - development
  
install:
  - haxelib install dox
  - haxelib install travix
  - haxelib run travix install

script:
  # - haxelib run travix interp
  # - haxelib run travix neko
#  # - haxelib run travix js
  # - haxelib run travix node
  # - haxelib run travix php
  # - haxelib run travix python
  # - haxelib run travix java
  # - haxelib run travix cs
  # - haxelib run travix cpp
  # - haxelib run travix flash -D exit
  - haxe doc.hxml
  - bash doc-deploy.sh
